steps:
- task: NodeTool@0
  displayName: 'Use Node 12.x'
  inputs:
    versionSpec: 12.x

- task: Npm@1
  displayName: 'npm ci'
  inputs:
    command: ci

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: custom
    customCommand: run build
