steps:
  - task: Npm@1
    displayName: "Lint"
    inputs:
      command: custom
      customCommand: run lint

  - task: ComponentGovernanceComponentDetection@0
    displayName: "Component Detection"
    condition: ne(variables['System.PullRequest.IsFork'], 'True')

  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: "SBoM Generation Task"
    inputs:
      BuildDropPath: "$(Build.ArtifactStagingDirectory)"
