steps:
- task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
  displayName: "SBoM Generation Task"
  inputs:
    BuildDropPath: "$(Build.ArtifactStagingDirectory)"

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: sbom'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/_manifest'
    ArtifactName: _manifest'
  # Only publish sbom from linux build since we use this to release and want to stay consistent
  condition: and(eq(variables['Agent.OS'], 'Linux'), ne(variables['System.PullRequest.IsFork'], 'True'))
